/** Subspecialty focus areas per main speciality — seeded into subspecialties. */
export const SUBSPECIALTY_SEEDS: Record<string, readonly string[]> = {
  'General Medicine': [
    'Primary care',
    'Chronic disease',
    'Preventive care',
    'Diabetes',
    'Hypertension',
    'Family medicine',
    'Adult medicine',
    'Internal medicine',
    'Geriatric care',
    'Travel medicine',
  ],
  Cardiology: [
    'Heart disease',
    'Hypertension',
    'ECG',
    'Heart failure',
    'Arrhythmia',
    'Chest pain',
    'Cholesterol',
    'Interventional cardiology',
    'Pediatric cardiology',
    'Cardiac rehabilitation',
  ],
  Dermatology: [
    'Acne',
    'Eczema',
    'Psoriasis',
    'Skin allergy',
    'Hair loss',
    'Cosmetic dermatology',
    'Pediatric dermatology',
    'Melanoma screening',
    'Rosacea',
    'Vitiligo',
  ],
  Pediatrics: [
    'Newborn care',
    'Child vaccination',
    'Growth monitoring',
    'Pediatric fever',
    'Child nutrition',
    'Developmental screening',
    'Adolescent medicine',
    'Pediatric asthma',
    'Neonatal care',
    'Behavioral pediatrics',
  ],
  Orthopedics: [
    'Joint pain',
    'Sports injuries',
    'Fractures',
    'Back pain',
    'Knee pain',
    'Physical therapy',
    'Arthritis',
    'Spine surgery',
    'Hand surgery',
    'Shoulder injuries',
  ],
  Neurology: [
    'Headache',
    'Migraine',
    'Epilepsy',
    'Stroke follow-up',
    'Neuropathy',
    'Memory disorders',
    "Parkinson's disease",
    'Multiple sclerosis',
    'Sleep disorders',
    'Movement disorders',
  ],
  Ophthalmology: [
    'Cataract',
    'Glaucoma',
    'Dry eye',
    'Vision correction',
    'Diabetic eye disease',
    'Pediatric eye care',
    'Retina disorders',
    'Corneal disease',
    'Strabismus',
    'Oculoplastic surgery',
  ],
  Dentistry: [
    'Root canal',
    'Teeth whitening',
    'Orthodontics',
    'Pediatric dentistry',
    'Dental implants',
    'Gum disease',
    'Cosmetic dentistry',
    'Oral surgery',
    'Prosthodontics',
    'TMJ disorders',
  ],
  Surgery: [
    'General surgery',
    'Laparoscopic surgery',
    'Hernia repair',
    'Gallbladder surgery',
    'Post-operative care',
    'Minor procedures',
    'Breast surgery',
    'Colorectal surgery',
    'Thyroid surgery',
    'Bariatric surgery',
  ],
  Emergency: [
    'Urgent care',
    'Trauma',
    'Acute illness',
    'First aid',
    '24/7 availability',
    'Critical care',
    'Pediatric emergency',
    'Toxicology',
    'Disaster medicine',
    'Resuscitation',
  ],
  Gynaecology: [
    'Pregnancy care',
    'Fertility',
    'Menstrual disorders',
    'PCOS',
    'Prenatal care',
    "Women's health",
    'Obstetrics',
    'Menopause care',
    'Gynecologic oncology',
    'Endometriosis',
  ],
  Nutritionist: [
    'Weight management',
    'Diabetes diet',
    'Sports nutrition',
    'Meal planning',
    'Child nutrition',
    'Bariatric nutrition',
    'Food allergy',
    'Eating disorders',
    'Prenatal nutrition',
    'Clinical nutrition',
  ],
  ENT: [
    'Sinusitis',
    'Hearing loss',
    'Tonsillitis',
    'Vertigo',
    'Sleep apnea',
    'Allergic rhinitis',
    'Voice disorders',
    'Ear infections',
    'Nasal polyps',
    'Thyroid nodules',
  ],
};

export function normalizeSubspecialtyName(raw: string): string {
  return raw.trim().slice(0, 40);
}

export function normalizeSubspecialtyKey(raw: string): string {
  return normalizeSubspecialtyName(raw).toLowerCase();
}
