/**
 * Curated Egypt-market medication names (trade + common generics).
 * Used to constrain AI prescription drafts to Egyptian pharmacy stock.
 */
export const EGYPT_MEDICATIONS = [
  'Panadol',
  'Panadol Extra',
  'Panadol Cold & Flu',
  'Brufen',
  'Cataflam',
  'Voltaren',
  'Aspocid',
  'Augmentin',
  'Amoxil',
  'Zithromax',
  'Klacid',
  'Cipro',
  'Flagyl',
  'Septrin',
  'Tavanic',
  'Unasyn',
  'Curam',
  'Hibiotic',
  'Omnicef',
  'Cefotax',
  'Zinnat',
  'E-Moxclav',
  'Antinal',
  'Enterogermina',
  'Imodium',
  'Motilium',
  'Primperan',
  'Gaviscon',
  'Nexium',
  'Controloc',
  'Pantoloc',
  'Omeprazole',
  'Losec',
  'Antodine',
  'Ranitidine',
  'Ventolin',
  'Symbicort',
  'Seretide',
  'Singulair',
  'Atrovent',
  'Aerius',
  'Telfast',
  'Zyrtec',
  'Clarityne',
  'Histazine',
  'Concor',
  'Atenolol',
  'Amlodipine',
  'Norvasc',
  'Capoten',
  'Coversyl',
  'Tritace',
  'Lasix',
  'Aldactone',
  'Aspirin Protect',
  'Plavix',
  'Lipitor',
  'Crestor',
  'Ator',
  'Zocor',
  'Glucophage',
  'Diamicron',
  'Amaryl',
  'Januvia',
  'Lantus',
  'NovoRapid',
  'Mixtard',
  'Thyroxine',
  'Euthyrox',
  'Eltroxin',
  'Prednisolone',
  'Dexamethasone',
  'Cortisone',
  'Betadine',
  'Fucidin',
  'Fucicort',
  'Locacorten',
  'Dermovate',
  'Mupirocin',
  'Opticrom',
  'Tobradex',
  'Floxal',
  'Otrivin',
  'Sinupret',
  'Mucosolvan',
  'Prospan',
  'Congestal',
  'Flu-out',
  'Catafast',
  'Arthrotec',
  'Myoflex',
  'Neurobion',
  'Milga',
  'Folvit',
  'Feroglobin',
  'Haemojet',
  'Calcium Sandoz',
  'Osteocare',
  'Vitamin D3',
  'Vidrop',
  'C-Retard',
  'Centrum',
  'Supradyn',
  'Daflon',
  'Detralex',
  'Xarelto',
  'Clexane',
  'Tramal',
  'Nalufin',
  'Ketolac',
  'Adol',
  'Paramol',
  'Cetamol',
  'Megamox',
  'Flumox',
  'Ultracillin',
  'Macrofuran',
  'Furadantin',
  'Diflucan',
  'Flucoral',
  'Daktarin',
  'Canesten',
  'Lamifen',
  'Lamisil',
  'Rivotril',
  'Xanax',
  'Stilnox',
  'Cipralex',
  'Zoloft',
  'Prozac',
  'Depakine',
  'Tegretol',
  'Keppra',
  'Sinemet',
  'Madopar',
] as const;

const NORMALIZED = new Map(
  EGYPT_MEDICATIONS.map((name) => [name.toLowerCase().replace(/\s+/g, ' ').trim(), name]),
);

/** Resolve a free-text med name to a catalog entry (exact / case-insensitive). */
export function matchEgyptMedication(name: string): string | null {
  const key = name.trim().toLowerCase().replace(/\s+/g, ' ');
  if (!key) return null;
  if (NORMALIZED.has(key)) return NORMALIZED.get(key)!;
  // Containment: catalog entry contained in AI text or vice versa (min 4 chars).
  for (const [norm, canonical] of NORMALIZED) {
    if (norm.length < 4) continue;
    if (key.includes(norm) || norm.includes(key)) return canonical;
  }
  return null;
}

export function egyptMedicationCatalogForPrompt(): string {
  return EGYPT_MEDICATIONS.join(', ');
}
